name: CI

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.6.15"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_CONNECT_DB: postgres
          POSTGRES_DB: travis
          POSTGRES_PASSWORD: postgres
        run: |
          pip install -e .
          (cd tests/data && python pytest_initdb.py)
          LZAPI_MODE="travis" pytest tests
